apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-oracle
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: block-oracle-config
          configMap:
            name: block-oracle-config
      containers:
        - name: block-oracle
          image: gcr.io/the-graph-staging/block-oracle:latest
          command:
            - /usr/local/bin/block-oracle
            - run
            - /etc/block-oracle/config.toml
          volumeMounts:
            - name: block-oracle-config
              mountPath: /etc/block-oracle
